name: tomato_app
description: Tomato Disease Detection App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  tflite_flutter: ^0.12.1
  image: ^4.1.3
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  http: ^1.2.0
  geolocator: ^14.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/tomato_model.tflite
    - assets/images/